-- What is the total revenue generated by the DVD rental business?
SELECT SUM(amount) AS total_revenue FROM payment;

-- How many rental transactions have been made?
SELECT COUNT(*) AS total_rentals FROM rental;

-- How many films are available in the inventory?
SELECT COUNT(film_id) AS total_film FROM film;

-- What is the average revenue generated per rental?
SELECT ROUND(AVG(amount), 2) AS avg_revenue FROM payment;

-- What is the monthly revenue trend?
SELECT 
    DATE_TRUNC('month', payment_date) AS month,
    SUM(amount) AS revenue
FROM payment
GROUP BY month
ORDER BY month;

-- How many rentals occur each month?
SELECT
	DATE_TRUNC('month', rental_date) AS month,
	COUNT(*) AS total_rentals
FROM rental
GROUP BY month
ORDER BY month;

-- Which store generates the most revenue?
SELECT 
	store.store_id,
	SUM(payment.amount) AS revenue
FROM payment 
JOIN rental ON payment.rental_id = rental.rental_id
JOIN inventory ON rental.inventory_id = inventory.inventory_id
JOIN store ON inventory.store_id = store.store_id
GROUP BY store.store_id
ORDER BY revenue DESC;

-- How many rentals are made by each store?
SELECT 
	store.store_id,
	COUNT(rental.rental_id) AS rental
FROM rental
JOIN inventory ON rental.inventory_id = inventory.inventory_id
JOIN store ON inventory.store_id = store.store_id
GROUP BY store.store_id
ORDER BY rental;

-- What are the top 5 most rented films?
SELECT 
	film.title,
	COUNT(rental.rental_id) AS rental
FROM film 
JOIN inventory ON film.film_id = inventory.film_id
JOIN rental ON inventory.inventory_id = rental.inventory_id
GROUP BY film.title
ORDER BY rental DESC
LIMIT 5;

-- Which films generate the highest revenue?
SELECT
	film.title,
	SUM(payment.amount) AS revenue
FROM payment
JOIN rental ON payment.rental_id = rental.rental_id
JOIN inventory on rental.inventory_id = inventory. inventory_id
JOIN film ON inventory.film_id = film.film_id
GROUP BY film.title
ORDER BY revenue DESC
LIMIT 10;

-- Who are the top customers by total payment?
SELECT
	customer.customer_id,
	customer.first_name,
	customer.last_name,
	SUM(payment.amount) AS total_payment
FROM customer
JOIN payment ON payment.customer_id = customer.customer_id
GROUP BY customer.customer_id, customer.first_name, customer.last_name
ORDER BY total_payment DESC
LIMIT 10;

-- How does monthly revenue vary across stores?
SELECT
	store.store_id,
	DATE_TRUNC('month', payment_date) AS month,
	SUM(amount) AS revenue
FROM payment
JOIN rental ON payment.rental_id = rental.rental_id
JOIN inventory ON rental.inventory_id = inventory.inventory_id
JOIN store ON inventory.store_id = store.store_id
GROUP BY store.store_id, month
ORDER BY store.store_id, month;

-- Rank films based on rental frequency
SELECT 
	film.title,
	COUNT(rental.rental_id) AS total_rental,
	RANK() OVER(ORDER BY COUNT(rental.rental_id) DESC) AS ranking
FROM film
JOIN inventory ON film.film_id = inventory.film_id
JOIN rental ON inventory.inventory_id = rental.inventory_id
GROUP BY film.film_id, film.title;

-- Rank stores by revenue performance.
SELECT
	store.store_id,
	SUM(payment.amount) AS revenue,
	RANK() OVER(ORDER BY SUM(payment.amount) DESC) AS rangking
FROM store
JOIN inventory ON store.store_id = inventory. store_id
JOIN rental ON inventory.inventory_id = rental.inventory_id
JOIN payment ON rental.rental_id = payment.rental_id
GROUP BY store.store_id;

